function sign bug fixed
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\cointiger.py", line 537, in sign
    auth += keys[i] + query[keys[i]]
TypeError: must be str, not int

replace by:
    auth += keys[i] + str(query[keys[i]])